from __future__ import annotations

from pathlib import Path

import mdtraj as md

from .base import FrameRecord
from .base import TrajectoryBackend


class MDTrajBackend(TrajectoryBackend):
    """Backend for standard trajectory formats supported by mdtraj."""

    def inspect(self) -> dict[str, object]:
        traj = self._load()
        return {
            "input_file": str(self.input_file),
            "topology_file": (
                str(self.topology_file) if self.topology_file else None
            ),
            "n_frames": traj.n_frames,
            "n_atoms": traj.n_atoms,
        }

    def iter_frames(self) -> list[FrameRecord]:
        traj = self._load()
        frames: list[FrameRecord] = []

        for i in range(traj.n_frames):
            xyz_text = md.formats.XYZTrajectoryFile._write_frame
            _ = xyz_text  # silence lint if unused during early development
            frame = traj[i]
            lines = self._frame_to_xyz_lines(frame)
            frames.append(
                FrameRecord(
                    frame_index=i,
                    file_type="xyz",
                    atom_count=frame.n_atoms,
                    lines=lines,
                    time_fs=float(frame.time[0]) if frame.time is not None else None,
                )
            )

        return frames

    def _load(self) -> md.Trajectory:
        if self.topology_file is not None:
            return md.load(str(self.input_file), top=str(self.topology_file))
        return md.load(str(self.input_file))

    def _frame_to_xyz_lines(self, frame: md.Trajectory) -> list[str]:
        top = frame.topology
        coords = frame.xyz[0]
        lines = ["Generated by MDTrajBackend\n"]

        for atom, xyz in zip(top.atoms, coords, strict=False):
            x, y, z = xyz
            lines.append(
                f"{atom.element.symbol:>4} "
                f"{x:>12.6f} {y:>12.6f} {z:>12.6f}\n"
            )
        return lines