"""Blender-based structure rendering helpers and UI."""

from .common import BondThresholdSpec, OrientationSpec, infer_title
from .workflow import (
    BlenderPreviewStructure,
    BlenderXYZRenderResult,
    BlenderXYZRenderSettings,
    BlenderXYZRenderWorkflow,
    build_blend_output_paths,
    build_bond_thresholds_for_structure,
    build_default_orientation_catalog,
    build_legend_output_paths,
    build_photoshoot_orientations,
    build_preset_orientations,
    build_render_output_paths,
    detect_structure_format,
    load_preview_structure,
    parse_pdb_records,
    parse_structure_records,
    read_pdb_comment,
    read_structure_comment,
    read_xyz_comment,
    render_atom_legend_image,
    render_script_path,
    resolve_blender_executable,
    resolve_desktop_dir,
    suggest_output_dir,
)

__all__ = [
    "BlenderPreviewStructure",
    "BlenderXYZRenderResult",
    "BlenderXYZRenderSettings",
    "BlenderXYZRenderWorkflow",
    "BondThresholdSpec",
    "OrientationSpec",
    "build_bond_thresholds_for_structure",
    "build_blend_output_paths",
    "build_default_orientation_catalog",
    "build_legend_output_paths",
    "build_photoshoot_orientations",
    "build_preset_orientations",
    "build_render_output_paths",
    "detect_structure_format",
    "infer_title",
    "load_preview_structure",
    "parse_pdb_records",
    "parse_structure_records",
    "read_pdb_comment",
    "read_structure_comment",
    "read_xyz_comment",
    "render_script_path",
    "render_atom_legend_image",
    "resolve_blender_executable",
    "resolve_desktop_dir",
    "suggest_output_dir",
]
