name: Build and Publish Docs on Dispatch

on:
  workflow_dispatch:

jobs:
  docs:
    uses: scikit-package/release-scripts/.github/workflows/_release-docs.yml@v0
    with:
      project: saxshell
      c_extension: false
      headless: true
      python_version: "3.12"
